### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [rajastakilos/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by rajastakilos** [comment]
Hey Billy,

I just added the mobile meta tag to the head of application.html.erb as per the instructions from Bootstrap.

Rajas

**Comment by rajastakilos** [comment]
Hi Billy,

Anything left to do on this?

**Comment by BillyMassey** [comment]
Looks Great! Keep up the awesome work 👍
